### ISSUE TITLE
 获取耐力值奖励失败: [ianus-token-auth] bad token; invalid signature

### ISSUE THREAD

**Issue by cktea** [AkenClub/ken-iMoutai-Script#6]
2024-10-14 09:09:00,756 - INFO - --------------------------
2024-10-14 09:09:00,756 - INFO - 🧾 用户："13055********，开始预约商品
2024-10-14 09:09:01,306 - INFO - 🛒 商品ID 10941 ✅ 预约成功: 申购完成，请于10月14日18:00查看预约申购结果
2024-10-14 09:09:01,866 - INFO - 🛒 商品ID 10942 ✅ 预约成功: 申购完成，请于10月14日18:00查看预约申购结果
2024-10-14 09:09:01,867 - INFO - 🎁 所有商品预约完成, 3 秒后获取耐力值奖励
2024-10-14 09:09:04,867 - INFO - 🏁 开始获取耐力值奖励
2024-10-14 09:09:05,309 - ERROR - 🚫 获取耐力值奖励失败: [ianus-token-auth] bad token; invalid signature
2024-10-14 09:09:08,311 - INFO - 🏁 查询 & 领取累计申购的小茅运
2024-10-14 09:09:08,723 - ERROR - 🚫 查询 & 领取累计申购的小茅运失败: 🚫 查询累计申购奖励失败: [ianus-token-auth] bad token; invalid signature
2024-10-14 09:09:11,725 - INFO - 🏁 查询 & 领取 7 日连续申购领取小茅运
2024-10-14 09:09:12,113 - ERROR - 🚫 7 日连续申购领取小茅运奖励异常: 🚫 查询 7 日连续申购失败: [ianus-token-auth] bad token; invalid signature

**Comment by AkenClub** [comment]
重新跑过第一二步脚本，把输出的设备 id 、 token 、cookie 那些重新填过一遍可以吗？

**Comment by AkenClub** [comment]
还有，你是第一次运行使用？还是之前可以用现在不行了？

**Comment by cktea** [comment]
重新过了一遍脚本，设置了变量！还是不行！不是第一次运行使用，之前就不能用，因为不影响申购使用，就没来反馈！

## 开始执行... 2024-10-14 13:50:06


2024-10-14 13:50:07,200 - INFO - 找到以下用户配置：
2024-10-14 13:50:07,200 - INFO - 用户 1: 📞 "13055********
2024-10-14 13:50:07,200 - INFO - 用户 2: 📞 "18359********
2024-10-14 13:50:07,200 - INFO - --------------------------
2024-10-14 13:50:07,201 - INFO - 🧾 用户："13055********，执行旅行
2024-10-14 13:50:07,590 - ERROR - 🚫 旅行失败: 🚫 获取用户数据 失败:[ianus-token-auth] bad token; invalid signature
Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/5_travel.py", line 351, in <module>
    page_data = get_user_isolation_page_data(user['DEVICE_ID'],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/5_travel.py", line 285, in get_user_isolation_page_data
    raise Exception(f"🚫 获取用户数据 失败:{body.get('message')}")
Exception: 🚫 获取用户数据 失败:[ianus-token-auth] bad token; invalid signature

## 执行结束... 2024-10-14 13:50:08  耗时 2 秒

**Comment by AkenClub** [comment]
![image](https://github.com/user-attachments/assets/e9b4df90-95e4-4bcc-aa3a-5b411f2d3ee8)
我现在重新跑一次脚本5，也没问题，脚本5和4部分接口是一样的所以结果一样的。你这个情况之前有人反馈过 #5 类似的，那时候也找不到原因。等我出现你们这种情况我再看是什么原因吧，没有你的环境复现不了

**Comment by AkenClub** [comment]
你青龙版本多少？看升版本有没有作用？我现在是青龙版本：正式版 v2.17.10

**Comment by cktea** [comment]
青龙面板是最新版本v2.17.11，尝试文中介绍，token和cookie 用jwt解开，设备ID和用户ID都对的上，重新拉库，重新过一遍脚本也试了，还是不行。

**Comment by AkenClub** [comment]
> 青龙面板是最新版本v2.17.11，尝试文中介绍，token和cookie 用jwt解开，设备ID和用户ID都对的上，重新拉库，重新过一遍脚本也试了，还是不行。

那我也不清楚了，你这个错是app接口返回来的，我也不知道为什么你预约能用，其他接口不能用，可能分了两套鉴权，也可能鉴权有效期问题，也可能拉黑了😥。如果是有效期问题或者app接口数据缓存问题的话，你可以试试过段时间再试试。也可以先用着预约先，有空上app手动获取一下耐力值和旅行就好，我们主要也是预约商品，对吧🤣

**Comment by AkenClub** [comment]
> 青龙面板是最新版本v2.17.11，尝试文中介绍，token和cookie 用jwt解开，设备ID和用户ID都对的上，重新拉库，重新过一遍脚本也试了，还是不行。

2.17.11 也可以用的，我现在升级都可以

**Comment by AkenClub** [comment]
Duplicate of #5

**Comment by AkenClub** [comment]
你好，你这个问题可以看看下面复现后的解决方法。

运行脚本返回 [ianus-token-auth] bad token; invalid signature 错误？

解决： 检查环境变量是否设置正确。出现该错误一般是因为 值 填了 KEN_IMAOTAI_ENV="13312345678$..$.."，脚本解析环境变量时 COOKIE 部分多了一个 "，导致报错。去除KEN_IMAOTAI_ENV=""即可，值 只填写真实获取到的数值就行。

注意：编辑变量弹窗里，名称的输入框内填固定值：KEN_IMAOTAI_ENV，值的输入框填真实信息：13312345678$..$..。下方示例中只展示值部分。

**Comment by axckck** [comment]
非常感谢，变量中删除 "  完美运行旅行
